### test the server is it's online ##########
GET http://localhost:35050


###################ADMIN TASKS########################

### authenticate ADMIN (login|)
POST http://localhost:35050/auth/adminlogin
content-type: application/json

{
    "email": "admin@shaper.co.za",
    "password": "@dmin@dmin1023"
}
###List all  admins################################
GET http://localhost:35050/auth/api/admin_records

####Get a list of all departments #################
GET http://localhost:35050/auth/api/department
 
###Get total number of  departments################
GET http://localhost:35050/auth/api/department_count




#### Add a new department##########################
POST http://localhost:35050/auth/api/add_department 
content-type: application/json

{
    "name": "Sales"
}


### authenticate Employee (login)####################
POST http://localhost:35050/user/api/employee_login
content-type: application/json

{
    "email": "lisa@shaper.co.za",
    "password": "password1"
}

#######get a list all employees####################
GET http://localhost:35050/auth/api/employees

########get total number of all employees###########
GET http://localhost:35050/auth/api/employee_count


###GET Employee Details##############################

 GET  http://localhost:35050/user/api/employees/me
